docs_dir: docs/book
site_dir: docs/html
nav:
    - index.md
    - Introduction: intro.md
    - "Quick Start": quick-start.md
    - Reference:
        - "Generating Responses": response.md
        - "Exceptions": exception.md
        - "Error Handling Middleware": middleware.md
        - "Not Found Handler": not-found-handler.md
site_name: Problem Details
site_description: 'Problem Details for PSR-7 Applications'
repo_url: 'https://github.com/mezzio/mezzio-problem-details'
