docs_dir: doc/book
site_dir: doc/html
nav:
    - index.md
    - Introduction: intro.md
    - "Quick Start": quick-start.md
    - Reference:
        - "Generating Responses": response.md
        - "Exceptions": exception.md
        - "Error Handling Middleware": middleware.md
site_name: Problem Details
site_description: 'Problem Details for PSR-7 Applications'
repo_url: 'https://github.com/weierophinney/problem-details'
extra_css:
    - css/mezzio.css
